wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.14.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686509310.88299
    t:
      1:
      - 1
      - 9
      - 37
      - 41
      - 55
      - 60
      - 82
      2:
      - 1
      - 9
      - 37
      - 41
      - 55
      - 60
      - 82
      3:
      - 7
      - 23
      4: 3.10.6
      5: 0.14.1
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
